---
- name: Ensure python-pycurl is installed
  yum: pkg=python-pycurl state=installed

- name: Ensure Elasticsearch signing key is installed
  rpm_key: key={{url_gpg_key}} state=present

- name: Ensure the repo file for ElasticSearch is ready at the destination machines
  copy: src=Elasticsearch-yum.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Ensure the repo file for ElasticSearch is ready at the destination machines
  copy: src=Logstash-yum.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644


- name: Ensure openjdk is installed
  yum:  pkg=java-1.7.0-openjdk state=installed

- name: Ensure ElasticSearch is installed
  yum: pkg=elasticsearch state=installed

