- hosts: logstashnodes
  sudo: True
  roles:
    - { role: logstash }

- hosts: searchnodes
  sudo: True
  roles:
    - { role: searchengine }

- hosts: kibananodes
  sudo: True
  roles:
    - { role: kibana }
