---

- name: restart logstash
  service: name=logstash state=restarted

- name: restart redis-server
  service: name=redis-server state=restarted

- name: restart redis
  service: name=redis state=restarted

- name: restart elasticsearch
  service: name=elasticsearch state=restarted

- name: restart apache2
  service: name=apache2 state=restarted

- name: restart httpd
  service: name=httpd state=restarted