---
# variables to define logstash installations
url_gpg_key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch

# Logstash repository (1.4.x)
url_logstash_pkg: http://packages.elasticsearch.org/logstash/1.4/debian

# Which file to be used as template to config the logstash/conf.d
logstash_conf:
  template: indexer.j2
  destination: /etc/logstash/conf.d/indexer.conf
