---

redis:
  deb:
    package: 'redis-server'
    service: 'redis-server'
  redhat:
    package: 'redis'
    service: 'redis'

redmon:
  service: 'redmon'
  deb:
    dependencies:
      - 'git'
      - 'ruby1.9.1'
      - 'ruby1.9.1-dev'      
      - 'g++'
      - 'make'
  redhat:
    dependencies:
      - 'git'
      - 'ruby1.9.3'
      - 'g++'
      - 'make'      
  gems:
    - 'bundler'
    - 'redmon'
  bin: '/usr/local/bin/redmon'
