---
- name: Ensure python-pycurl is installed
  apt: pkg=python-pycurl state=installed

- name: Ensure Elasticsearch signing key is installed
  apt_key: url={{url_es_gpg_key}} state=present

- name: Ensure Elasticsearch 1.2.x repository is installed
  apt_repository: repo="deb {{url_es_reop_1_2}} stable main" state=present update_cache=yes

- name: Ensure elasticsearch is installed
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre
    - elasticsearch state=installed
