---
- name: Ensure python-pycurl is installed
  apt: pkg=python-pycurl state=installed

- name: Ensure elasticsearch signing key is installed
  apt_key: url={{url_es_gpg_key}} state=present

- name: Ensure elasticsearch 1.2.x repository is installed
  apt_repository: repo="deb {{url_elasticsearch_pkg}} stable main" state=present update_cache=yes

- name: Ensure elasticsearch is installed
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre
    - elasticsearch state=installed

- name: Ensure elasticsearch config is in place
  copy: src=elasticsearch.yml
        dest=/etc/elasticsearch/elasticsearch.yml
        owner=root group=root mode=0644
  copy: src=elasticsearch.yml
        dest=/etc/elasticsearch/elasticsearch.yml
        owner=root group=root mode=0644
  notify:
    - restart elasticsearch

- name: Ensure elasticsearch boots on startup
  shell: update-rc.d elasticsearch defaults
  notify:
    - restart elasticsearch
