---
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure elasticsearch config is in place
  copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch
