
- name: Ensure elasticsearch apt signing key is installed
  apt_key: url={{ url_gpg_key }} state=present

- name: Ensure logstash repository is installed
  apt_repository: repo="deb {{ url_logstash_pkg }} stable main" update_cache=yes

- name: Ensure java and logstash are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - openjdk-7-jre
    - logstash

#- name: Ensure logstash service is run as the root user
#  copy: src=logstash
#        dest=/etc/init.d/logstash
#        owner=root group=root mode=0755
#  notify:
#    - restart logstash

- name: Ensure logstash config is in place
  copy: src=shipper.conf
        dest=/etc/logstash/conf.d/shipper.conf
        owner=root group=root mode=0644
  notify:
    - restart logstash

- name: Ensure logstash boots on startup
  shell: update-rc.d logstash defaults
  notify:
    - restart logstash

- name: Change log file permission
  raw: chmod 644 /var/log/auth.log  /var/log/kern.log  /var/log/syslog
  notify:
    - restart logstash
